language: node_js
sudo: false
jdk:
- openjdk7
node_js:
- '4'
- '6'
- '7'
env:
- ELASTIC_VERSION="3.2.5" ELASTIC_URL=https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.3.0/elasticsearch-2.3.0.tar.gz
- ELASTIC_VERSION="5.0.1" ELASTIC_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.0.1.tar.gz
before_install:
- curl -s $ELASTIC_URL | tar xz -C /tmp || true
- /tmp/elasticsearch-${ELASTIC_VERSION}/bin/elasticsearch &
